export type AppRole = 'OWNER' | 'MANAGER' | 'TREASURER' | 'MEMBER' | 'VIEWER';

export type AppPermission =
  | 'MESS_VIEW'
  | 'MESS_MANAGE'
  | 'MEMBERS_VIEW'
  | 'MEMBERS_MANAGE'
  | 'MEALS_VIEW'
  | 'MEALS_MANAGE'
  | 'BAZAR_VIEW'
  | 'BAZAR_MANAGE'
  | 'EXPENSES_VIEW'
  | 'EXPENSES_MANAGE'
  | 'EXPENSES_APPROVE'
  | 'LEDGER_VIEW'
  | 'LEDGER_MANAGE'
  | 'SETTLEMENT_VIEW'
  | 'SETTLEMENT_MANAGE'
  | 'REPORTS_VIEW'
  | 'REPORTS_EXPORT'
  | 'SETTINGS_VIEW'
  | 'SETTINGS_MANAGE'
  | 'AUDIT_VIEW';

export const ROLE_PERMISSIONS: Record<AppRole, AppPermission[]> = {
  OWNER: [
    'MESS_VIEW',
    'MESS_MANAGE',
    'MEMBERS_VIEW',
    'MEMBERS_MANAGE',
    'MEALS_VIEW',
    'MEALS_MANAGE',
    'BAZAR_VIEW',
    'BAZAR_MANAGE',
    'EXPENSES_VIEW',
    'EXPENSES_MANAGE',
    'EXPENSES_APPROVE',
    'LEDGER_VIEW',
    'LEDGER_MANAGE',
    'SETTLEMENT_VIEW',
    'SETTLEMENT_MANAGE',
    'REPORTS_VIEW',
    'REPORTS_EXPORT',
    'SETTINGS_VIEW',
    'SETTINGS_MANAGE',
    'AUDIT_VIEW',
  ],
  TREASURER: [
    'MESS_VIEW',
    'MEMBERS_VIEW',
    'MEALS_VIEW',
    'BAZAR_VIEW',
    'BAZAR_MANAGE',
    'EXPENSES_VIEW',
    'EXPENSES_MANAGE',
    'EXPENSES_APPROVE',
    'LEDGER_VIEW',
    'LEDGER_MANAGE',
    'SETTLEMENT_VIEW',
    'SETTLEMENT_MANAGE',
    'REPORTS_VIEW',
    'REPORTS_EXPORT',
    'SETTINGS_VIEW',
  ],
  MANAGER: [
    'MESS_VIEW',
    'MESS_MANAGE',
    'MEMBERS_VIEW',
    'MEMBERS_MANAGE',
    'MEALS_VIEW',
    'MEALS_MANAGE',
    'BAZAR_VIEW',
    'BAZAR_MANAGE',
    'EXPENSES_VIEW',
    'EXPENSES_MANAGE',
    'EXPENSES_APPROVE',
    'LEDGER_VIEW',
    'LEDGER_MANAGE',
    'SETTLEMENT_VIEW',
    'SETTLEMENT_MANAGE',
    'REPORTS_VIEW',
    'REPORTS_EXPORT',
    'SETTINGS_VIEW',
    'SETTINGS_MANAGE',
    'AUDIT_VIEW',
  ],
  MEMBER: [
    'MESS_VIEW',
    'MEMBERS_VIEW',
    'MEALS_VIEW',
    'BAZAR_VIEW',
    'EXPENSES_VIEW',
    'LEDGER_VIEW',
    'SETTLEMENT_VIEW',
    'REPORTS_VIEW',
  ],
  VIEWER: [
    'MESS_VIEW',
    'MEMBERS_VIEW',
    'MEALS_VIEW',
    'REPORTS_VIEW',
  ],
};
